# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-01 14:53
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trainsched', '0002_auto_20160331_2218'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trainroute',
            name='transfers',
        ),
    ]
