# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-07 19:43
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('trainsched', '0003_remove_trainroute_transfers'),
    ]

    operations = [
        migrations.AddField(
            model_name='trainroute',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2016, 4, 7, 19, 43, 33, 901782, tzinfo=utc)),
            preserve_default=False,
        ),
    ]
