# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-07 19:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trainsched', '0004_trainroute_created'),
    ]

    operations = [
        migrations.AddField(
            model_name='trainroute',
            name='transfers',
            field=models.TextField(default=''),
        ),
    ]
