# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-08 11:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trainsched', '0005_trainroute_transfers'),
    ]

    operations = [
        migrations.RenameField(
            model_name='trainroute',
            old_name='travelTime',
            new_name='duration',
        ),
        migrations.AddField(
            model_name='trainroute',
            name='trainName',
            field=models.CharField(default='filler name', max_length=100),
            preserve_default=False,
        ),
    ]
