# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-08 12:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trainsched', '0007_auto_20160408_1152'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trainroute',
            name='id',
        ),
        migrations.AddField(
            model_name='trainroute',
            name='primary_key',
            field=models.CharField(default='hi', max_length=100, primary_key=True, serialize=False),
            preserve_default=False,
        ),
    ]
