# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-08 20:04
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trainsched', '0008_auto_20160408_1249'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trainroute',
            name='arrival',
        ),
        migrations.RemoveField(
            model_name='trainroute',
            name='departure',
        ),
        migrations.RemoveField(
            model_name='transfer',
            name='arrival',
        ),
        migrations.RemoveField(
            model_name='transfer',
            name='departure',
        ),
        migrations.AddField(
            model_name='trainroute',
            name='date',
            field=models.DateField(default=datetime.datetime(2016, 4, 8, 20, 3, 55, 335329)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='trainroute',
            name='time',
            field=models.TimeField(default=datetime.time(20, 4, 5, 63255)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='trainroute',
            name='timeStart',
            field=models.TimeField(default=datetime.time(20, 4, 17, 270631)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='transfer',
            name='timeArr',
            field=models.TimeField(default=datetime.time(20, 4, 27, 494634)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='transfer',
            name='timeDep',
            field=models.TimeField(default=datetime.time(20, 4, 37, 902289)),
            preserve_default=False,
        ),
    ]
