# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-08 20:26
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trainsched', '0009_auto_20160408_2004'),
    ]

    operations = [
        migrations.RenameField(
            model_name='trainroute',
            old_name='time',
            new_name='timeEnd',
        ),
    ]
